spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gerenciador_eventos
    username: admin
    password: 26260290
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      enabled: true
      file: compose.yml